#Email settings
spring.mail:
  from: mail@example.com
  username: mail@example.com
  password: ******
  host: smtp.example.com
  port: 465
  protocol: smtps

#Email settings for gmail.com
#spring.mail:
#  username: username@gmail.com
#  password: ******
#  host: smtp.gmail.com
#  port: 587
#  properties:
#    mail.smtp.starttls.enable = true

#Server listening settings
#server:
#  address: 0.0.0.0
#  port: 8080

#Monitoring settings
#monitor:
#  #Number of threads for testing (already set up, change if needed)
#  thread-pool-size: 5
#  #Number of days to keep test results
#  keep-test-results: 90

#Loggin level settings, set for debug
#logging.level:
#  ru.doublebyte.availabilitymonitor: DEBUG
