#Email settings
spring.mail:
  from: mail@example.com
  username: mail@example.com
  password: ******
  host: smtp.example.com
  port: 465
  protocol: smtps

#Email settings for gmail.com
#spring.mail:
#  username: username@gmail.com
#  password: ******
#  host: smtp.gmail.com
#  port: 587
#  properties:
#    mail.smtp.starttls.enable = true

#Database connection
#spring.datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:./database
#    username: sa
#    password:

#Monitoring settings
#monitor:
#  #Number of threads for testing (already set up, change if needed)
#  thread-pool-size: 5

#Loggin level settings, set for debug
#logging.level:
#  ru.doublebyte.availabilitymonitor: DEBUG
